### ISSUE TITLE
connectycube_flutter_call_kit When will it support iOS?

### ISSUE THREAD

**Issue by Basemshawwa** [ConnectyCube/connectycube-flutter-call-kit#31] opened 2021-12-28 16:36 UTC
connectycube_flutter_call_kit When will it support iOS? please

**Comment by TatankaConCube** [comment] 2022-01-05 17:25
the duplicate of https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues/3

**Closed by TatankaConCube** 2022-01-05 17:25 UTC
