### ISSUE TITLE
Call sound stops after few seconds

### ISSUE THREAD

**Issue by imrishuroy** [ConnectyCube/connectycube-flutter-call-kit#78] opened 2022-12-01 18:19 UTC
The ring sound plays for a few seconds when there is an incoming call and then stops. Please let me know what happens.

**Comment by TatankaConCube** [comment] 2023-04-19 13:53
I can't reproduce it on my side. Could you check this issue on the latest version (2.2.4)? Or close this ticket if this issue is no more actually for you.

**Comment by TatankaConCube** [comment] 2024-02-12 09:48
no activity for a long time, closing

**Closed by TatankaConCube** 2024-02-12 09:48 UTC
