### ISSUE TITLE
Connectycube - flutter Accept button launches the app

### ISSUE THREAD

**Issue by alito0697** [ConnectyCube/connectycube-flutter-call-kit#92] opened 2023-02-21 17:09 UTC
![Open](https://user-images.githubusercontent.com/112117615/220413093-98cb7b60-fa26-4f45-ad56-7715883f2949.png)

when i receive an incoming call while the app is terminated the **Accept button launches the app instead of executing _joinMeetingVideo() a top-level method**
here is the code :
` 
  
        videocaller()async{
            
            Uuid uuid = Uuid();

            SharedPreferences prefs = await SharedPreferences.getInstance();

            dynamic username = prefs.getString("username");

            CallEvent callEvent = CallEvent(sessionId: uuid.v4() ,callType: 0, callerId: 2, callerName: username, opponentsIds:{1234});

      Future _onCallAccepted(CallEvent callEvent) async {
      _joinMeetingVideo();
     }

     Future _onCallRejected(callEvent) async {

       }
      Future onCallRejectedWhenTerminated(CallEvent callEvent) async {
        print("reject call");
    }
        Future onCallAcceptedWhenTerminated(CallEvent callEvent) async {
      _joinMeetingVideo();
       }
       ConnectycubeFlutterCallKit.onCallRejectedWhenTerminated = onCallRejectedWhenTerminated;
       ConnectycubeFlutterCallKit.onCallAcceptedWhenTerminated = onCallAcceptedWhenTerminated;
      ConnectycubeFlutterCallKit.instance.init(
        onCallAccepted: _onCallAccepted,
        onCallRejected: _onCallRejected,
      );
      ConnectycubeFlutterCallKit.showCallNotification(callEvent);
      ConnectycubeFlutterCallKit.setOnLockScreenVisibility(isVisible: true);
    }`

**Comment by TatankaConCube** [comment] 2023-02-22 08:52
the duplicate of https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues/85

**Closed by TatankaConCube** 2023-02-22 08:52 UTC
