### ISSUE TITLE
connectycube_flutter_call_kit When will it support iOS? please

### ISSUE THREAD

**Issue by Basemshawwa** [ConnectyCube/connectycube-flutter-call-kit#33] opened 2021-12-31 18:59 UTC
connectycube_flutter_call_kit When will it support iOS? please

**Comment by TatankaConCube** [comment] 2022-01-05 17:30
duplicate of https://github.com/ConnectyCube/connectycube-flutter-call-kit/issues/3 
just FYI we have a work branch [feature/add_ios_support](https://github.com/ConnectyCube/connectycube-flutter-call-kit/tree/feature/add_ios_support) but it is unstable and has some differences between iOS and Android API and we still work on this feature.

**Closed by TatankaConCube** 2022-01-05 17:30 UTC
